@startuml E-learning 画面遷移図
hide circle
skinparam linetype ortho 
title 画面遷移図[E-learning]



entity "ページの名前" as ページの名前 {
  やる事
  --
  ページ内のコンテンツ
  ・ボタン、リンク
}


entity "ログイン" as ログイン {
  認証
  --
  入力フォーム:ID/PASS
  ・ログインボタン
  ・新規登録アカウント作成リンク
  ・パスワード再発行リンク
}

entity "新規アカウント作成" as 新規登録 {
  生徒・講師アカウント作成
  --
  入力フォーム:色々
  ・新規登録ボタン
}
entity "パスワード再発行" as パスワード再発行 {
  Emailヘ再発行リンク送信
  --
  メールアドレス入力フォーム
  ・パスワード再発行ボタン
}

entity "管理者メイン" as 管理者メイン {
  ・講師一覧ページ
  ・戻る
  ・ログイン
  ・ログアウト
}

entity "講師一覧ページ" as 講師一覧ページ {
    講師アカウントの管理
  --
  ・講師登録、編集、削除、ステータス確認（？）
}

'---以下~~~~まで講師メインページ配下-------------------------

entity "講師メイン" as 講師メイン {
  通知画面（予定・タスク）
  ・生徒一覧
  ・生徒日報確認
  ・my動画一覧
  ・テスト作成フォーム
  ・アカウント設定（講師）
  ・戻る
  ・ログイン
  ・ログアウト
}
entity "生徒一覧" as 生徒一覧 {
  生徒アカウントの管理
  --
  ・生徒登録、編集、削除、ステータス確認（？）
}
entity "生徒日報一覧" as 生徒日報一覧 {
  生徒日報の管理
  --
  ・生徒日報の確認
}

entity "my動画一覧" as my動画一覧 {
  登録した動画の管理
  --
  ・ファイルアップロード
  ・タイトル内容タグ等編集
  ・テストとの紐づけ
  ・ステータス確認（視聴回数、スター率）
}
entity "テスト作成フォーム" as テスト作成フォーム {
  作成したテストの管理
  --
  ・テスト作成、編集、削除、ステータス確認（受験回数、正答率）
}
entity "講師アカウント設定" as 講師アカウント設定 {
  メールアドレス
  パスワード
  ・編集ボタン
}
entity "講師プロフィール設定" as 講師プロフィール設定 {
  詳細なプロフィール色々
  ・編集ボタン
}
'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


'---以下~~~~まで生徒メインページ配下-------------------------
entity "生徒メインページ" as 生徒メインページ {
  ・日報一覧
  ・動画一覧
  ・テスト一覧
  ・問題演習
  ・アカウント設定
  ・戻る
  ・ログイン
  ・ログアウト
}
entity "問題演習" as 問題演習 {
  自分用回答用紙の作成
  --
}
entity "実績一覧確認" as 実績一覧確認 {
  動画視聴、テスト受験、問題演習の履歴成績の一覧表示
  --

}

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


'#######################################################
'以下のコードを触ると矢印（関係性）を変更できる。
'たまにエラー出るのでこまめに保存とプレビュー推奨
'文字を選択した状態でCtrl + D で同じ文字列を複数選択可、一気に編集できる。
'#######################################################

ログイン-->新規登録
ログイン-->パスワード再発行

ログイン-->管理者アカウント
管理者アカウント-->管理者メイン

ログイン-->生徒アカウント
生徒アカウント-->生徒メインページ

ログイン-->講師アカウント
講師アカウント-->講師メイン

管理者メイン-->講師一覧ページ
' 講師一覧ページ-->講師メイン
管理者アカウント-->生徒アカウント
管理者アカウント-->講師アカウント

新規登録-->確認画面
確認画面-->完了画面
パスワード再発行-->確認画面2
確認画面2-->完了画面2


'---以下~~~~まで講師メインページ配下-------------------------

講師メイン-->生徒一覧
' 生徒一覧-->生徒メインページ
講師メイン-->生徒日報一覧
講師メイン-->my動画一覧
講師メイン-->テスト作成フォーム
講師メイン-->講師アカウント設定
講師アカウント設定-->講師プロフィール設定

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


'---以下~~~~まで生徒メインページ配下-------------------------

生徒メインページ-->日報一覧
日報一覧-->日報編集etc
生徒メインページ-->動画一覧

動画一覧-->動画視聴ページ
動画視聴ページ-->テスト受験
テスト一覧-->テスト受験
生徒メインページ-->テスト一覧
生徒メインページ-->問題演習
生徒メインページ-->実績一覧確認

生徒メインページ-->生徒アカウント設定
生徒アカウント設定-->生徒プロフィール設定

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~









@enduml